# Generated by Django 3.2.9 on 2021-11-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('Roll_Number', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(default='', max_length=100)),
                ('FatherName', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=500)),
                ('Cell_Number', models.IntegerField(max_length=20)),
                ('Admission_Date', models.DateField()),
                ('BForm', models.ImageField(default='', upload_to='images/')),
                ('Promised_Fee', models.IntegerField(max_length=99999)),
            ],
            options={
                'db_table': 'std_registration',
            },
        ),
    ]
